In [10]:
import pandas as pd

df= pd.read_csv('../data/titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [11]:
# Show how many missing values
df.isnull().sum()

# IMPUTATION is when we fill in missing values. 
# We use mean if data is symmetric without extreme outliers.
# If data is skewed we use MEDIAN IMPUTATION (e.g., more kids than adults).
# Modal imputation is more useful when we deal with categorical data.

# For "Age" maybe data was lost/not recorded. 
# We can't delete these people (we'd lose ~20% of our data), so we use Imputation.
# To fix this for Age, we replace with the middle value (Median Imputation).
# fillna searches for "NaN" values.

df['Age'] = df['Age'].fillna(df['Age'].median())

# DELETE (DROP) Cabin because it's noise.
# NB: inplace=True means that we change the DataFrame directly, not returning a copy.
df.drop(columns=['Cabin'], inplace=True)

# Show how many missing values remain after imputation and dropping Cabin
df.isnull().sum()

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [12]:
##IN OUR MODEL WE REPLACE WORDS WITH NUMBERS LIKE ASSIGN MALE TO 0 AND FEMALES TO 1
## WE CAN USE :

## y=w_1*SEX + w_2*AGE + b

# Create a dictionary to map the values
gender_map = {'male': 1, 'female': 0}

# Apply the map to the 'Sex' column
df['Sex'] = df['Sex'].map(gender_map)

# Check the table again
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,S

In [13]:
# List the columns we want to throw away because they don't help our model
cols_to_drop = ['Name', 'Ticket', 'PassengerId']

# Drop them from our DataFrame
df.drop(columns=cols_to_drop, inplace=True)

# Let's see our clean 'Matrix'
print(df.head())

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    1  22.0      1      0   7.2500        S
1         1       1    0  38.0      1      0  71.2833        C
2         1       3    0  26.0      0      0   7.9250        S
3         1       1    0  35.0      1      0  53.1000        S
4         0       3    1  35.0      0      0   8.0500        S

In [ ]:
##LEARNING ONE-HOT ENCODING
import pandas as pd

# Example Titanic data with 'Embarked' column
data = {
    'PassengerId': [1, 2, 3, 4],
    'Embarked': ['S', 'C', 'Q', 'S']
}
df = pd.DataFrame(data)

# Show the original DataFrame
print("Original DataFrame:")
print(df)

#  One-Hot Encoding
# pd.get_dummies automatically converts categorical values into binary flags (0/1).
# columns=['Embarked'] → tells pandas which column to encode
# drop_first=True → drops the first category ('C') to avoid redundancy
# Why? Because if Embarked_S=0 and Embarked_Q=0, we already know the passenger embarked at C.
# Keeping all three columns would cause multicollinearity (perfectly predictable columns),
# which breaks some ML algorithms.
df_encoded = pd.get_dummies(df, columns=['Embarked'], drop_first=True)

# Show the transformed DataFrame
print("\nDataFrame after One-Hot Encoding:")
print(df_encoded)

# ✅ One-Hot Encoding in Action:
# Embarked_S → 1 if embarked at S, else 0
# Embarked_Q → 1 if embarked at Q, else 0
# If both are 0 → embarked at C (the dropped category)

# Final check of column data types
print("\nColumn data types:")
print(df_encoded.dtypes)

In [14]:
# Convert 'Embarked' into multiple binary columns

## pd.get_dummies → built‑in Pandas function that converts categorical
## drop_first=True → drops the first category (C in this case) to avoid redundancy.
## Because if both Embarked_S=0 and Embarked_Q=0, the model automatically knows the passenger embarked at C.

df = pd.get_dummies(df, columns=['Embarked'], drop_first=True)

# Final check of our data types
print(df.dtypes)
df.head()

Survived        int64
Pclass          int64
Sex             int64
Age           float64
SibSp           int64
Parch           int64
Fare          float64
Embarked_Q       bool
Embarked_S       bool
dtype: object

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_Q  Embarked_S
0         0       3    1  22.0      1      0   7.2500       False        True
1         1       1    0  38.0      1      0  71.2833       False       False
2         1       3    0  26.0      0      0   7.9250       False        True
3         1       1    0  35.0      1      0  53.1000       False        True
4         0       3    1  35.0      0      0   8.0500       False        True

In [15]:
# The Target (y) is what we want to predict
# It’s the answer key: did the passenger survive (1) or not (0)?

y = df['Survived'] #This selects the column "Survived" from the Titanic dataset
#Shape: (891,) → a vector with 891 entries (one per passenger).

# The Features (X) are the clues we use to predict it
# We drop 'Survived' from X because the model shouldn't see the answer!

X = df.drop(columns=['Survived']) # i.e use every column except for "survive" to calculate "survive"
# We hide the answers from model

print("Target Shape (vector):", y.shape)
print("Feature Matrix Shape:", X.shape)

Target Shape (vector): (891,)
Feature Matrix Shape: (891, 8)