In [14]:
import pandas as pd

df= pd.read_csv('../data/titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [15]:
# Show how many missing values
df.isnull().sum()

# IMPUTATION is when we fill in missing values. 
# We use mean if data is symmetric without extreme outliers.
# If data is skewed we use MEDIAN IMPUTATION (e.g., more kids than adults).
# Modal imputation is more useful when we deal with categorical data.

# For "Age" maybe data was lost/not recorded. 
# We can't delete these people (we'd lose ~20% of our data), so we use Imputation.
# To fix this for Age, we replace with the middle value (Median Imputation).
# fillna searches for "NaN" values.

df['Age'] = df['Age'].fillna(df['Age'].median())

# DELETE (DROP) Cabin because it's noise.
# NB: inplace=True means that we change the DataFrame directly, not returning a copy.
df.drop(columns=['Cabin'], inplace=True)

# Show how many missing values remain after imputation and dropping Cabin
df.isnull().sum()

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [16]:
##IN OUR MODEL WE REPLACE WORDS WITH NUMBERS LIKE ASSIGN MALE TO 0 AND FEMALES TO 1
## WE CAN USE :

## y=w_1*SEX + w_2*AGE + b

# Create a dictionary to map the values
gender_map = {'male': 1, 'female': 0}

# Apply the map to the 'Sex' column
df['Sex'] = df['Sex'].map(gender_map)

# Check the table again
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,S